#!/usr/bin/python3

import os
from pathlib import Path
from datetime import date
import argparse

parser = argparse.ArgumentParser(description="Backup config files")
parser.add_argument("-u", "--update_upstream", action='store_true')
args = parser.parse_args()

home = str(Path.home())

home_white_list = [
    ".bash_profile",
    ".profile",
    ".bashrc",
    ".spacemacs",
    ".tmux.conf",
    ".vimrc",
    ".xbindkeysrc",
    ".xkbcomp",
    ".Xmodmap",
    ".Xresources",
    ".tmux",
    ".gitconfig",
    ".doom.d",
    ".makepkg.conf",
    "scripts",
    ".zshenv",
    ".zshrc",
]

dot_config_white_list = [
    "autorandr",
    "autostart",
    "fish",
    "flake8",
    "flameshot",
    "fontconfig",
    "hn-tui.toml",
    "i3",
    "i3status",
    "kak",
    "kak-lsp",
    "kitty",
    "light",
    "omf",
    "picom.conf",
    "yapf",
    "systemd",
    ".projectile",
    "spotify-player",
    "iterm2",
    "nvim",
    "input-remapper"
]

cwd = os.path.dirname(__file__)


# add git modules first
if not os.path.exists(f"{cwd}/.config/kak/plugins/plug.kak"):
    os.system(
        f"""
    cd {cwd} && git submodule add https://github.com/robertmeta/plug.kak.git \
    .config/kak/plugins/plug.kak
  """
    )
if not os.path.exists(f"{cwd}/.config/kak/plugins/kakoune-surround"):
    os.system(
        f"""
    cd {cwd} && git submodule add https://github.com/h-youhei/kakoune-surround.git \
    .config/kak/plugins/kakoune-surround
  """
    )
if not os.path.exists(f"{cwd}/.config/kak/plugins/fzf.kak"):
    os.system(
        f"""
    cd {cwd} && git submodule add https://github.com/andreyorst/fzf.kak.git \
    .config/kak/plugins/fzf.kak
  """
    )
if not os.path.exists(f"{cwd}/.config/kitty/kitty-themes"):
    os.system(
        f"""
      cd {cwd} && git submodule add https://github.com/dexpota/kitty-themes \
      .config/kitty/kitty-themes
    """
    )
if not os.path.exists(f"{cwd}/.tmux/plugins/tpm"):
    os.system(
        f"""
    git submodule add https://github.com/tmux-plugins/tpm \
    .tmux/plugins/tpm
  """
    )
if not os.path.exists(f"{cwd}/.tmux/plugins/tmux"):
    os.system(
        f"""
    cd {cwd} && git submodule add https://github.com/dracula/tmux \
    .tmux/plugins/tmux
  """
    )

for f in os.listdir(home):
    if f in home_white_list:
        os.system(f"cp -r ~/{f} {cwd}")

os.system("mkdir -p .config")
for f in os.listdir("{}/.config".format(home)):
    if f in dot_config_white_list:
        os.system(f"cp -r ~/.config/{f} {cwd}/.config")

# list all globally installed packages using yarn into package.json
os.system(f"cp ~/.config/yarn/global/package.json {cwd}/package.json")

# list all explicitly installed packages into packages.txt
# NOTE: disable for non-Linux OS
# os.system(f"pacman -Qe > {cwd}/packages.txt")
# os.system(f"cp /desktopfs-pkgs.txt > {cwd}/")

# Copy .ssh config file
os.system(f"mkdir -p {cwd}/.ssh && cp ~/.ssh/config {cwd}/.ssh")

# commit/push new changes using git
if args.update_upstream:
  os.system(
      f'cd {cwd} && \
    git add . && \
    git commit -m "backup configs {date.today().strftime("%Y-%m-%d")}"'
  )
  os.system(f"cd {cwd} && git push")
