##############################
# Theme and layout
###############################

# relative line numbers
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ wrap

source "%val{config}/dracula.kak"

###############################
# Indenting and autocomplete
###############################

#Use Tab for both indenting and completion
hook global InsertChar \t %{ try %{
  execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
}}
hook global InsertDelete ' ' %{ try %{
  execute-keys -draft 'h<a-h><a-k>\A\h+\z<ret>i<space><esc><lt>'
}}
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

# Tab sizes
hook global InsertChar \t %{ exec -draft -itersel h@ }
set global tabstop 4
set global indentwidth 4

###############################
# Languages support
###############################

# Add scheme support for racket
hook global BufCreate .+\.(rkt) %{
    set-option buffer filetype scheme
}

# Add sh support for .conf files
hook global BufCreate .+\.(conf) %{
    set-option buffer filetype sh
}

# change indent width to 2 for a subset of languages
hook global WinSetOption filetype=(scheme|c|cpp|python|yaml) %{
    set global tabstop 2
    set global indentwidth 2
}

###############################
# Keys mapping
###############################

# System clipboard interactions
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | pbcopy
}}
map global user P '!pbpaste<ret>' -docstring 'paste before the beginning of a selection using clipboard'
map global user p '<a-!>pbpaste<ret>' -docstring 'paste after the end of a selection using clipboard'
map global user r '<a-d>!pbpaste<ret>' -docstring 'replace a selection with yanked text using clipboard'

# save file
map global normal '<c-s>' :write<ret> -docstring 'save file'
map global normal '<c-q>' :quit!<ret> -docstring 'force quit'

# comment
map global normal '#' :comment-line<ret> -docstring 'comment line'
map global normal '<a-#>' :comment-block<ret> -docstring 'comment block'

# map goto a specific line in a file
map global goto p -docstring 'Go to the current cursor''s grep position' '<esc>: grep-jump<ret>'

# edit kakrc
map global user e ':edit ~/.config/kak/kakrc<ret>' -docstring 'edit kakrc'

# other bindings
map global normal -docstring 'Select all occurrences of the current selection' '<a-%>' '*%s<ret>'
map global normal -docstring 'Select next occurrence of the current selection' '<c-n>' '*N'
map global normal -docstring 'Select previous occurrence of the current selection' '<c-p>' '*<a-N>'
