article_parse_command = {command = "article_md", options = []}

url_open_command = "open"

[keymap.global_keymap]
quit = "q"
goto_previous_view = "backspace"

[[keymap.custom_keymap.custom_view_navigation]]
key = "M-1"
tag = "story"
by_date = true
[keymap.custom_keymap.custom_view_navigation.numeric_filters]
elapsed_days_interval = {start = 0, end = 1}
points_interval = {start = 100}

[[keymap.custom_keymap.custom_view_navigation]]
key = "M-2"
tag = "story"
by_date = false
[keymap.custom_keymap.custom_view_navigation.numeric_filters]
elapsed_days_interval = {start = 0, end = 3}

[[keymap.custom_keymap.custom_view_navigation]]
key = "M-3"
tag = "story"
by_date = false
[keymap.custom_keymap.custom_view_navigation.numeric_filters]
elapsed_days_interval = {start = 0, end = 7}
