# article_parse_command = {command = "_article_md", options = ["--format", "html"]}
# article_parse_command = { command = "mercury-parser", options = [] }
# use_pacman_loading = false
# use_page_scrolling = false

# [keymap.comment_view_keymap]
# next_comment = ["J", "j"]

[[keymap.custom_keymaps]]
key = "M-1"
tag = "story"
by_date = true
[keymap.custom_keymaps.numeric_filters]
elapsed_days_interval = {start = 0, end = 1}
points_interval = {start = 100}

[[keymap.custom_keymaps]]
key = "M-2"
tag = "story"
by_date = false
[keymap.custom_keymaps.numeric_filters]
elapsed_days_interval = {start = 0, end = 3}

[[keymap.custom_keymaps]]
key = "M-3"
tag = "story"
by_date = false
[keymap.custom_keymaps.numeric_filters]
elapsed_days_interval = {start = 0, end = 7}
