#!/bin/bash

# xdotool key --clearmodifiers ctrl+c

file=$(mktemp)
xsel -ob > $file
kitty --class floating kak $file
# remove the newline from eol
truncate -s -1 $file
cat $file | xsel -ib

xdotool key --clearmodifiers ctrl+v
