#!/bin/fish

set OPT "-aq"
set SRC "/home/aome510/"
set SNAP "/data/snapshots/home/"
set LAST "/data/snapshots/home/last"
set LINK "--link-dest=$LAST" 
set date (date "+%y-%m-%d_%T")

# not the first time running the backup script
if test -d $LAST
    rsync $OPT $LINK $SRC $SNAP$date
    rm -f $LAST
else
    rsync -a --quiet $SRC $SNAP$date
end

ln -s $SNAP$date/ $LAST

# Backup /etc folder
rsync -a --quiet --delete /etc /data 2> /dev/null
