use-grammars = { except = [ "hare" ] }

[[language]]
name = "python"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true
